// src/App.jsx
import React from 'react';
import { Routes, Route, useLocation } from 'react-router-dom';
import { TransitionGroup, CSSTransition } from 'react-transition-group';
import IntroView from './pages/IntroView';
import QuizView from './pages/QuizView';
import ResultView from './pages/ResultView';

function App() {
  const location = useLocation();

  return (
    <div className="quiz-container min-h-screen flex flex-col relative overflow-hidden">
      <TransitionGroup component={null}>
        <CSSTransition
          key={location.pathname}
          timeout={500}
          classNames="slide-right"
          unmountOnExit
        >
          <div className="page">
            <Routes location={location}>
              <Route path="/" element={<IntroView />} />
              <Route path="/quiz" element={<QuizView />} />
              <Route path="/result" element={<ResultView />} />
            </Routes>
          </div>
        </CSSTransition>
      </TransitionGroup>
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div class="quiz-container min-h-screen flex flex-col">
    <router-view v-slot="{ Component, route }">
      <transition 
        :name="route.meta.transition || 'slide-right'" 
        mode="out-in"
      >
        <component :is="Component" :key="route.path" />
      </transition>
    </router-view>
  </div>
</template>

<script setup>
// App.vue는 루트 컴포넌트로 모든 페이지의 레이아웃을 담당합니다
</script>
